### PR TITLE
Add Qt-based client library

### LINKED ISSUE #52: media-hub: convert client library to Qt
This task is about converting the client library of media-hub to use Qt types. Branches are linked to this issue.

### PR DESCRIPTION
**Pull request by mardy**
Add libmedia-hub-qt, a client library which uses Qt classes.

### CODE REVIEW

**Comment by cibersheep** [comment]
This looks solved in the latest version



--- 


~~This is what I have experienced on Arale, on RC then installing the ppa (from 15/11):~~
Case a
- Open Podbird
- Tap on an episode
- Tap on a different episode

The cover and info of episode is not shown. This is true for any other episode selected
- Tap twice on an episode will shoe cover and info

Case b
- Open Music app
- Tap on a song
- Cover and info are not shown
- Music is stopped
- If tap on play it will play last song which info was loaded

If tap twice on a song it will load cover and info

Case c
- Play podcast
- Take a screenshot
- Screenshot effect doesn't sound
- ¿Camera? Volume will be set (in my case lower)
- Second screenshot will play screenshot effect and audio volume will be restored

[media-hub.log](https://github.com/ubports/media-hub/files/7590683/media-hub.log)

[application-click-com.mikeasoft.podbird_Podbird_0.8.13.log](https://github.com/ubports/media-hub/files/7590684/application-click-com.mikeasoft.podbird_Podbird_0.8.13.log)

**Comment by cibersheep** [comment]
I've been testing the last changes of the library and looks like issues I was experimenting are solved

**Comment by mardy** [comment]
@Flohack74 Do I have your permission to merge this? :-)

**Comment by fredldotme** [comment]
One thing I noticed on the PinePhone: It doesn't support hw video playback at all right now.
What used to happen was the video player complaining rightfully about the codec not being supported in the UI.
With this branch applied the UI doesn't complain anymore and pauses immediately.

If this is the case for Halium ports where video playback might not be enabled at start then I see this as a regression.

**Comment by fredldotme** [comment]
Another one, this time one the Pixel 3a with TELEports and sending myself a compressed MP4, trying to view it.
Not only is playback choppy, TELEports crashes when trying to play a video, pausing it, and trying to play it again.
Here's a backtrace of it:

```
Thread 13 "QSGRenderThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7166d5deb0 (LWP 9234)]
0x000000714951c2f8 in lomiri::MediaHub::VideoSink::transformationMatrix() const
    () from /usr/lib/aarch64-linux-gnu/libMediaHub.so.5
(gdb) bt
#0  0x000000714951c2f8 in lomiri::MediaHub::VideoSink::transformationMatrix() const () from /usr/lib/aarch64-linux-gnu/libMediaHub.so.5
#1  0x00000071492a461c in ShaderVideoMaterial::updateTexture() ()
   from /usr/lib/aarch64-linux-gnu/qt5/plugins/video/videonode/libshadervideonode.so
#2  0x0000007191fac294 in QSGRenderer::preprocess() ()
   from /usr/lib/aarch64-linux-gnu/libQt5Quick.so.5
#3  0x0000007191fabba8 in QSGRenderer::renderScene(QSGBindable const&) ()
   from /usr/lib/aarch64-linux-gnu/libQt5Quick.so.5
#4  0x0000007191fabff0 in QSGRenderer::renderScene(unsigned int) ()
   from /usr/lib/aarch64-linux-gnu/libQt5Quick.so.5
#5  0x0000007191fe5258 in QSGDefaultRenderContext::renderNextFrame(QSGRenderer*, unsigned int) () from /usr/lib/aarch64-linux-gnu/libQt5Quick.so.5
#6  0x0000007192043590 in QQuickWindowPrivate::renderSceneGraph(QSize const&)
    () from /usr/lib/aarch64-linux-gnu/libQt5Quick.so.5
#7  0x0000007191ff0ed0 in ?? ()
   from /usr/lib/aarch64-linux-gnu/libQt5Quick.so.5
#8  0x00000071921d0708 in ?? ()
   from /usr/lib/aarch64-linux-gnu/libQt5Quick.so.5
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) 
```

**Comment by mardy** [comment]
> Another one, this time one the Pixel 3a with TELEports and sending myself a compressed MP4, trying to view it. Not only is playback choppy, TELEports crashes when trying to play a video, pausing it, and trying to play it again.

I've debugged this a bit, and I see that when asked to playback a video, TELEports instantiates **two** media players. Valgrind complains about memory issues in libhybris: https://paste.ubuntu.com/p/F53cp9FmQN/

My guess is that the old client library in some way was not letting the client get into such a situation, whereas I tryed to remove all the obstacles that would prevent us from playing back two videos at once. So it looks like we've hit the hybris limitation that @peat-psuwit was mentioned in Telegram...

**Comment by mardy** [comment]
OK, I think I fixed this issue: the last commit fixes the crash in TELEports, whereas [this PR](https://gitlab.com/ubports/apps/teleports/-/merge_requests/429) (to TELEports) fixes the choppy (or sometimes completely missing) video playback.

**Review by fredldotme — APPROVED** [review]
LGTM

**Pull request merged**
