### PR TITLE
Put Jenkinsfile into right place

### PR DESCRIPTION
**Pull request by amartinz**

### CODE REVIEW

**Review by mardy — APPROVED** [review]

**Comment by Flohack74** [comment]
@amartinz normally that move is only needed when the repo was migrated to Gitlab and our CI has been adapted. Did the job refuse to trigger?

**Comment by amartinz** [comment]
i was moving it just in case it wouldn't and if we move the repo to gitlab because of the ongoing migration.

i did it together with https://github.com/ubports/media-hub/pull/46 but that PR is not valid anymore because we are moving away from using the Android rootfs for the sounds.

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
This is not necessary until the move to GitLab is done. Jenkins doesn't look for `debian/Jenkinsfile` on GitHub.

**Comment by amartinz** [comment]
I meant to press "Close with comment" before, my bad.

**Pull request closed without merging**
